// Generated by gencpp from file pyCAS/DoorStatus.msg
// DO NOT EDIT!


#ifndef PYCAS_MESSAGE_DOORSTATUS_H
#define PYCAS_MESSAGE_DOORSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pyCAS
{
template <class ContainerAllocator>
struct DoorStatus_
{
  typedef DoorStatus_<ContainerAllocator> Type;

  DoorStatus_()
    : header()
    , door_type()  {
    }
  DoorStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , door_type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _door_type_type;
  _door_type_type door_type;





  typedef boost::shared_ptr< ::pyCAS::DoorStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pyCAS::DoorStatus_<ContainerAllocator> const> ConstPtr;

}; // struct DoorStatus_

typedef ::pyCAS::DoorStatus_<std::allocator<void> > DoorStatus;

typedef boost::shared_ptr< ::pyCAS::DoorStatus > DoorStatusPtr;
typedef boost::shared_ptr< ::pyCAS::DoorStatus const> DoorStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pyCAS::DoorStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pyCAS::DoorStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pyCAS::DoorStatus_<ContainerAllocator1> & lhs, const ::pyCAS::DoorStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.door_type == rhs.door_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pyCAS::DoorStatus_<ContainerAllocator1> & lhs, const ::pyCAS::DoorStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pyCAS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pyCAS::DoorStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyCAS::DoorStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyCAS::DoorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyCAS::DoorStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyCAS::DoorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyCAS::DoorStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pyCAS::DoorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d8b2485e25d4907a5e3fe5f1bcb0a2e";
  }

  static const char* value(const ::pyCAS::DoorStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d8b2485e25d4907ULL;
  static const uint64_t static_value2 = 0xa5e3fe5f1bcb0a2eULL;
};

template<class ContainerAllocator>
struct DataType< ::pyCAS::DoorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pyCAS/DoorStatus";
  }

  static const char* value(const ::pyCAS::DoorStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pyCAS::DoorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string door_type\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pyCAS::DoorStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pyCAS::DoorStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.door_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoorStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pyCAS::DoorStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pyCAS::DoorStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "door_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.door_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYCAS_MESSAGE_DOORSTATUS_H
