// Generated by gencpp from file pyCAS/ObstacleStatus.msg
// DO NOT EDIT!


#ifndef PYCAS_MESSAGE_OBSTACLESTATUS_H
#define PYCAS_MESSAGE_OBSTACLESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pyCAS
{
template <class ContainerAllocator>
struct ObstacleStatus_
{
  typedef ObstacleStatus_<ContainerAllocator> Type;

  ObstacleStatus_()
    : header()
    , obstacle_data()  {
    }
  ObstacleStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacle_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _obstacle_data_type;
  _obstacle_data_type obstacle_data;





  typedef boost::shared_ptr< ::pyCAS::ObstacleStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pyCAS::ObstacleStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleStatus_

typedef ::pyCAS::ObstacleStatus_<std::allocator<void> > ObstacleStatus;

typedef boost::shared_ptr< ::pyCAS::ObstacleStatus > ObstacleStatusPtr;
typedef boost::shared_ptr< ::pyCAS::ObstacleStatus const> ObstacleStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pyCAS::ObstacleStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pyCAS::ObstacleStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pyCAS::ObstacleStatus_<ContainerAllocator1> & lhs, const ::pyCAS::ObstacleStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obstacle_data == rhs.obstacle_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pyCAS::ObstacleStatus_<ContainerAllocator1> & lhs, const ::pyCAS::ObstacleStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pyCAS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pyCAS::ObstacleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyCAS::ObstacleStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyCAS::ObstacleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyCAS::ObstacleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyCAS::ObstacleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyCAS::ObstacleStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pyCAS::ObstacleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01f13ac50bca8d8a91c4495d3ee892ae";
  }

  static const char* value(const ::pyCAS::ObstacleStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01f13ac50bca8d8aULL;
  static const uint64_t static_value2 = 0x91c4495d3ee892aeULL;
};

template<class ContainerAllocator>
struct DataType< ::pyCAS::ObstacleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pyCAS/ObstacleStatus";
  }

  static const char* value(const ::pyCAS::ObstacleStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pyCAS::ObstacleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string obstacle_data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pyCAS::ObstacleStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pyCAS::ObstacleStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacle_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pyCAS::ObstacleStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pyCAS::ObstacleStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obstacle_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.obstacle_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYCAS_MESSAGE_OBSTACLESTATUS_H
