// Generated by gencpp from file pyCAS/RobotStatus.msg
// DO NOT EDIT!


#ifndef PYCAS_MESSAGE_ROBOTSTATUS_H
#define PYCAS_MESSAGE_ROBOTSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pyCAS
{
template <class ContainerAllocator>
struct RobotStatus_
{
  typedef RobotStatus_<ContainerAllocator> Type;

  RobotStatus_()
    : header()
    , location_row(0)
    , location_col(0)
    , heading(0.0)  {
    }
  RobotStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , location_row(0)
    , location_col(0)
    , heading(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _location_row_type;
  _location_row_type location_row;

   typedef int8_t _location_col_type;
  _location_col_type location_col;

   typedef float _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::pyCAS::RobotStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pyCAS::RobotStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatus_

typedef ::pyCAS::RobotStatus_<std::allocator<void> > RobotStatus;

typedef boost::shared_ptr< ::pyCAS::RobotStatus > RobotStatusPtr;
typedef boost::shared_ptr< ::pyCAS::RobotStatus const> RobotStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pyCAS::RobotStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pyCAS::RobotStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pyCAS::RobotStatus_<ContainerAllocator1> & lhs, const ::pyCAS::RobotStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.location_row == rhs.location_row &&
    lhs.location_col == rhs.location_col &&
    lhs.heading == rhs.heading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pyCAS::RobotStatus_<ContainerAllocator1> & lhs, const ::pyCAS::RobotStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pyCAS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pyCAS::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyCAS::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyCAS::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyCAS::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyCAS::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyCAS::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pyCAS::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18461a44b0d1a2987df9514e09c45ef0";
  }

  static const char* value(const ::pyCAS::RobotStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18461a44b0d1a298ULL;
  static const uint64_t static_value2 = 0x7df9514e09c45ef0ULL;
};

template<class ContainerAllocator>
struct DataType< ::pyCAS::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pyCAS/RobotStatus";
  }

  static const char* value(const ::pyCAS::RobotStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pyCAS::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 location_row\n"
"int8 location_col\n"
"float32 heading\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pyCAS::RobotStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pyCAS::RobotStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.location_row);
      stream.next(m.location_col);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pyCAS::RobotStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pyCAS::RobotStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "location_row: ";
    Printer<int8_t>::stream(s, indent + "  ", v.location_row);
    s << indent << "location_col: ";
    Printer<int8_t>::stream(s, indent + "  ", v.location_col);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYCAS_MESSAGE_ROBOTSTATUS_H
