// Generated by gencpp from file pyCAS/TaskRequest.msg
// DO NOT EDIT!


#ifndef PYCAS_MESSAGE_TASKREQUEST_H
#define PYCAS_MESSAGE_TASKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pyCAS
{
template <class ContainerAllocator>
struct TaskRequest_
{
  typedef TaskRequest_<ContainerAllocator> Type;

  TaskRequest_()
    : Header()
    , id(0)
    , goal_x(0)
    , goal_y(0)
    , data()  {
    }
  TaskRequest_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , id(0)
    , goal_x(0)
    , goal_y(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _goal_x_type;
  _goal_x_type goal_x;

   typedef uint8_t _goal_y_type;
  _goal_y_type goal_y;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::pyCAS::TaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pyCAS::TaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TaskRequest_

typedef ::pyCAS::TaskRequest_<std::allocator<void> > TaskRequest;

typedef boost::shared_ptr< ::pyCAS::TaskRequest > TaskRequestPtr;
typedef boost::shared_ptr< ::pyCAS::TaskRequest const> TaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pyCAS::TaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pyCAS::TaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pyCAS::TaskRequest_<ContainerAllocator1> & lhs, const ::pyCAS::TaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.id == rhs.id &&
    lhs.goal_x == rhs.goal_x &&
    lhs.goal_y == rhs.goal_y &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pyCAS::TaskRequest_<ContainerAllocator1> & lhs, const ::pyCAS::TaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pyCAS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pyCAS::TaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pyCAS::TaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyCAS::TaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pyCAS::TaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyCAS::TaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pyCAS::TaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pyCAS::TaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c55ab525a6c1d56131fcd172d61cde19";
  }

  static const char* value(const ::pyCAS::TaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc55ab525a6c1d561ULL;
  static const uint64_t static_value2 = 0x31fcd172d61cde19ULL;
};

template<class ContainerAllocator>
struct DataType< ::pyCAS::TaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pyCAS/TaskRequest";
  }

  static const char* value(const ::pyCAS::TaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pyCAS::TaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Header\n"
"uint8 id\n"
"uint8 goal_x\n"
"uint8 goal_y\n"
"string data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pyCAS::TaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pyCAS::TaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.id);
      stream.next(m.goal_x);
      stream.next(m.goal_y);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pyCAS::TaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pyCAS::TaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "goal_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_x);
    s << indent << "goal_y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_y);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYCAS_MESSAGE_TASKREQUEST_H
